name: Performance testing

on:
  push:
#    branches: [ main ]
    branches: [ MCIL-105-base-performance-tests ]

env:
  HOST: https://mil-d-apim.azure-api.net

jobs:
  Performance_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: 3.x
      - name: Install requirements
        run: |
          python3 --version
          python3 -m pip install --user pipenv
          python3 -m pipenv sync
      - name: Performance testing with Locust
        run: |
          python3 -m pipenv run locust -f src/locustfile.py \
              --headless \
              --host $HOST \
              --users 1 \
              --spawn-rate 1 \
              --run-time 30 \
              --exit-code-on-error 0 \
              --csv report.csv \
              --html report.html
        env:
          CLIENT_CREDENTIALS_BASE64: ${{ secrets.CLIENT_CREDENTIALS_BASE64 }}
      - name: Performance test summary
        run: |
          req_total=$(awk -F',' 'END {print $3}' report.csv_stats.csv)
          req_fail=$(awk -F',' 'END {print $4}' report.csv_stats.csv)
          fail_rate=$(( (req_fail + req_total) / 100 ))
          rps=$(awk -F',' 'END {print $10}' report.csv_stats.csv)
          p90=$(awk -F',' 'END {print $16}' report.csv_stats.csv)
          p95=$(awk -F',' 'END {print $17}' report.csv_stats.csv)
          p99=$(awk -F',' 'END {print $19}' report.csv_stats.csv)
          
          echo Fail Rate: ${fail_rate}%
          echo RPS: $rps
          echo 90 Percentile: ${p90}ms
          echo 95 Percentile: ${p95}ms
          echo 99 Percentile: ${p99}ms
      - name: Store locust report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: locust-report
          path: report.html
